version: '3'
services:
  fluentd-srv:
    image: registry.cn-hangzhou.aliyuncs.com/sqmall/fluentd:r1.5
    # image: gcr.azk8s.cn/fluentd-elasticsearch/fluentd:v2.5.2
    # image: fluentd:v0.0.2
    # entrypoint: 
      # - /bin/bash
      # - -c
    # command: ["chown -R fluent:fluent /var/target/ && tini -- /bin/entrypoint.sh fluentd"]
    restart: always
    environment: 
      ES_HOST: sq-log-es
      ES_PORT: 9200
    volumes:
    - ./fluent.conf:/fluentd/etc/fluent.conf
    - fluentd-srv-buffer:/fluentd/buffers:rw
    # - ./fluent.conf:/etc/fluent/config.d/fluent.conf
    # - /Users/david/flora_run/logs:/var/target/fauna:rw
    - ./Shanghai:/etc/localtime:ro
    ports:
    - 24224:24224
    networks:
    - es_net
# privileged: true
volumes:
  fluentd-srv-buffer:
networks:
  es_net:
    external: true
  