version: '3'
services:
  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/sqmall/kibana:oss-6.8.0
    environment:
      # - elasticsearch.hosts=http://10.20.0.46:9200
      ELASTICSEARCH_HOSTS: http://sq-log-es:9200
    container_name: kibana
    ports:
      - "5601:5601"
    # volumes:
      # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - es_net
networks:
  es_net:
    external: true