version: '3'
services:
  jenkins-docker:
    image: h1kkan/jenkins-docker:2.164.3-alpine
    restart: always
    volumes:
    #- ./my.cnf:/etc/mysql/conf.d/my.cnf
    - jenkins-home:/var/jenkins_home
    - ./Shanghai:/etc/localtime:ro
    ports:
    - 7070:8080
    - 5000:5000
volumes:
  jenkins-home: