version: '2'
services:
  es:
    image: registry.cn-hangzhou.aliyuncs.com/sqmall/elasticsearch:6.6.1.2
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      NODE_NAME: my-es
      CLUSTER_NAME: my-es-cluster
    container_name: es 
    ports:
      - "4592:9200"
      - "4593:9300"
    volumes:
      - es-datavolume:/usr/share/elasticsearch/data
volumes:
  es-datavolume:
